version: 2

jobs:
  build:
    docker:
      - image: cimg/rust:1.47.0
        auth:
          username: aokellermann
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Format
          command: cargo fmt -- --check
      - run:
          name: Lint
          command: cargo clippy -- -D warnings
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
